AppBundle\Entity\Event:
    type: entity
    table: event
    repositoryClass: AppBundle\Entity\Repository\EventRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        description:
            type: string
            length: 255
        start:
            type: datetime
            nullable: true
        end:
            type: datetime
            nullable: true
        location:
            type: string
            length: 255
        comment:
            type: string
            length: 255
            nullable: true
        createdAt:
            type: datetime
            column: created_at
            nullable: true
            default: CURRENT_TIMESTAMP
        modifiedAt:
            type: datetime
            column: modified_at
            nullable: true
            default: CURRENT_TIMESTAMP
    lifecycleCallbacks: {  }
